Import('rtconfig')
Import('RTT_ROOT')

from building import *
import os

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
MCUX_Config/clock_config.c
MCUX_Config/pin_mux.c
""")

CPPPATH = [cwd, cwd + '/MCUX_Config', cwd + '/ports']
CPPDEFINES = ['CPU_MIMXRT1189CVM8C_cm7', 'MIMXRT1189_cm7_SERIES', 'FSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1', 'ARM_MATH_CM7']

if GetDepend(['BSP_USING_ETH']):
    CPPDEFINES += ['SDK_NETC_USED=1', 'FSL_ETH_ENABLE_CACHE_CONTROL=1']

if GetDepend(['RT_USING_CHERRYUSB']):
    cherryusb_path = os.path.join(RTT_ROOT, 'components', 'drivers', 'usb', 'cherryusb')
    src += ['cherryusb_port.c']
    if GetDepend(['RT_CHERRYUSB_DEVICE_TEMPLATE_CDC_ACM']):
        src += ['cherryusb_cdc_acm.c']
    if GetDepend(['BSP_CHERRYUSB_HOST_MOUSE_DEMO']):
        src += ['usbh_mouse_demo.c']
    CPPPATH += [
        cherryusb_path,
        os.path.join(cherryusb_path, 'common'),
        os.path.join(cherryusb_path, 'core'),
        os.path.join(cherryusb_path, 'class', 'hub'),
        os.path.join(cherryusb_path, 'class', 'cdc'),
        os.path.join(cherryusb_path, 'class', 'hid'),
    ]

if rtconfig.PLATFORM in ['gcc']:
    CPPDEFINES += ['__STARTUP_INITIALIZE_RAMFUNCTION']

if rtconfig.PLATFORM in ['armcc', 'armclang']:
    # CPPDEFINES += ['SDK_DEBUGCONSOLE']
    CPPDEFINES += ['NDEBUG']

if rtconfig.PLATFORM in ['iccarm']:
    CPPDEFINES += ['NDEBUG']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
